### ISSUE TITLE
Checking out line 8 causes a crash

### ISSUE THREAD

**Issue by dqnk** [siggsy/travana-android#1]
When tapping on the bus line number 8 at any station where the line stops in the app (for instance Gosposvetska), the app crashes and returns to station overview instead of showing the map with bus stops. This might be because the line had changed recently to Gameljne-Brnčičeva (before it was Brod-Brnčičeva due to construction work on the road) and some bus stops were changed/added.

**Comment by siggsy** [comment]
Something appears to be wrong with the LPP API. Bus line 8 returns empty list of stations when trying to request for route arrivals.

The app crashes because of an assumption that when the API reports success it gives a non empty list of station arrivals. There is an easy fix, but it will only get rid of the crash by displaying a blank page with "Gameljne-Brnčičeva" title. I don't see how this would be any less broken.

I will notify people maintaining the LPP API.
